//
//  Color.swift
//  Lingua Quest
//
//  Created by siam on 14/07/2026.
//

import SwiftUI



extension Color {
//    static let appPrimary = Color("PrimaryColor")
//    static let appSecondary = Color("SecondaryColor")
//    static let appBackground = Color("BackgroundColor")
//    static let appTextPrimary = Color("TextPrimaryColor")
//    static let appTextSecondary = Color("TextSecondaryColor")
//    static let appError = Color("ErrorColor")
//    static let appSuccess = Color("SuccessColor")
    
    
    // NOTE: The following colors are auto-generated by Xcode from Assets.xcassets:
    // .appPrimary (from "AppPrimaryColor")
    // .appSecondary (from "AppSecondaryColor")
    // .primaryButtonText (from "PrimaryButtonText")
    // .secondaryButtonText (from "SecondaryButtonText")
    // .activeLevel (from "activeLevel")
    
    // UI Components Colors
    static let appBackgroundLightBlue = Color("BackgroundLightBlue")
    static let appBorderBrown = Color("BorderBrown")
    static let appBorderLightBlue = Color("BorderLightBlue")
    static let appGlowTeal = Color("GlowTeal")
    static let appGlowYellow = Color("GlowYellow")
    static let appIconBrown = Color("IconBrown")
    static let appTextBrown = Color("TextBrown")
    static let appTextDarkBlue = Color("TextDarkBlue")
}
