//
//  Color.swift
//  Lingua Quest
//
//  Created by siam on 14/07/2026.
//

import SwiftUI



extension Color {
    static let appPrimaryColor = Color("AppPrimaryColor")
//    static let appSecondaryColor = Color("AppSecondaryColor")
//    static let appBackground = Color("BackgroundColor")
//    static let appTextPrimary = Color("TextPrimaryColor")
//    static let appTextSecondary = Color("TextSecondaryColor")
//    static let appError = Color("ErrorColor")
//    static let appSuccess = Color("SuccessColor")
    
    
    // NOTE: The following colors are auto-generated by Xcode from Assets.xcassets:
    // .appPrimary (from "AppPrimaryColor")
    // .appSecondary (from "AppSecondaryColor")
    // .primaryButtonText (from "PrimaryButtonText")
    // .secondaryButtonText (from "SecondaryButtonText")
    // .activeLevel (from "activeLevel")
    
    // UI Components Colors
    static let appBackgroundLightBlue = Color("BackgroundLightBlue")
    static let appBorderBrown = Color("BorderBrown")
    static let appBorderLightBlue = Color("BorderLightBlue")
    static let appGlowTeal = Color("GlowTeal")
    static let appGlowYellow = Color("GlowYellow")
    static let appIconBrown = Color("IconBrown")
    static let appTextBrown = Color("TextBrown")
    static let appTextDarkBlue = Color("TextDarkBlue")
    static let appViewBackground  = Color("ViewBackground")
    
    /// Profile Screen Colors
    // LinguaAvatarView Colors
    static let appBadgeBrown = Color("BadgeBrown")                       // #683D00
    
    // Stat Card Colors
    static let appProfileCardBackground = Color("ProfileCardBackground") // #F9F3EB
    static let appProfileCardBorder = Color("ProfileCardBorder")         // #DAC2AE
    static let appProfileTextDark = Color("ProfileTextDark")             // #1D1B17
    static let appProfileTextMuted = Color("ProfileTextMuted")           // #544434
    
    // Profile Stats Icons Colors
    static let appProfileCoinsIcon = Color("ProfileCoinsIconColor")     // #895100
    static let appProfileXPIcon = Color("ProfileXPIconColor")           // #006A62
    static let appProfileStreakIcon = Color("ProfileStreakIconColor")   // #BF0025
    static let appProfileWorldsIcon = Color("ProfileWorldsIconColor")   // #877462
}
