//
//  PromptFactory.swift
//  Lingua Quest
//
//  Created by taqieallah on 25/07/2026.
//

import Foundation

enum PromptFactory {
    static func createLiveSessionPrompt(scenario: BossScenario) -> String {
        return """
        You are \(scenario.bossName).
        Role Context: \(scenario.roleDescription)
        
        The user is trying to accomplish the following objective:
        "\(scenario.objective)"
        
        Keep your replies concise (1-3 sentences), stay completely in character, and respond naturally as if in a real conversation.
        Never use markdown or emojis. Never break character. Do not tell the user what their objective is, let them drive the conversation.
        """
    }
    
    static func createBossEvaluationPrompt(scenario: BossScenario, transcript: String) -> String {
        return """
        You are an expert language evaluator. Review the following conversation transcript between a User and a Persona.
        
        Persona: \(scenario.bossName)
        User Objective: \(scenario.objective)
        
        TRANSCRIPT:
        \(transcript)
        
        Evaluate whether the User successfully completed their objective.
        IMPORTANT: The transcript is generated by Speech-to-Text software. Ignore any obvious hallucinations, background noise transcriptions, or sudden unexplained shifts in language (e.g., random words in Welsh, Hindi, etc.) that do not make sense in context. Evaluate based on the user's clear intents.
        
        You must output ONLY a valid JSON object matching the following schema exactly, with no markdown formatting or backticks:
        {
            "task_completed": boolean,
            "fluency_score": integer between 0 and 100,
            "feedback_message": "string providing short, constructive feedback on their performance"
        }
        """
    }
}
