//
//  PromptFactory.swift
//  Lingua Quest
//
//  Created by taqieallah on 25/07/2026.
//

import Foundation

enum PromptFactory {
    private static func getTargetLanguageName() -> String {
        if let name = UserDefaults.standard.string(forKey: AppConstants.UserDefaultsKeys.targetLanguageName), !name.isEmpty {
            return name
        }
        if let code = UserDefaults.standard.string(forKey: AppConstants.UserDefaultsKeys.learningLanguageCode),
           let lang = AppLanguage.targetLanguages.first(where: { $0.code.caseInsensitiveCompare(code) == .orderedSame }) {
            return lang.name
        }
        return "the target language"
    }
    
    static func createLiveSessionPrompt(scenario: BossScenario) -> String {
        let targetLang = getTargetLanguageName()
        return """
        CRITICAL LANGUAGE INSTRUCTION:
        You MUST conduct this entire conversation ONLY in \(targetLang). Under NO circumstances should you speak, translate, or respond in English or any other language, even if the user speaks to you in English or another language, or asks for a translation. All of your responses must be strictly, fluently, and naturally in \(targetLang).

        You are \(scenario.bossName).
        Role Context: \(scenario.roleDescription)
        
        The user is trying to accomplish the following objective:
        "\(scenario.objective)"
        
        Keep your replies concise (1-3 sentences), stay completely in character, and respond naturally as if in a real conversation.
        Never use markdown or emojis. Never break character. Do not tell the user what their objective is, let them drive the conversation.
        
        OFF-TOPIC / OUT-OF-SCENARIO RULE:
        If the user says anything that is off-topic, irrelevant to your role context or scenario, or breaks character (for example, talking about unrelated topics or asking general non-roleplay questions), you MUST immediately notify/remind them in \(targetLang) (staying strictly in character) that what they said is outside the scenario or irrelevant, and politely steer them back to focus on their objective.
        """
    }
    
    static func createBossEvaluationPrompt(scenario: BossScenario, transcript: String) -> String {
        let appLangCode = UserDefaults.standard.string(forKey: AppConstants.UserDefaultsKeys.appLanguage) ?? "en"
        let feedbackLang = appLangCode == "ar" ? "Arabic" : "English"
        let targetLang = getTargetLanguageName()
        
        return """
        You are an expert language evaluator. Review the following conversation transcript between a User and a Persona.
        
        Persona: \(scenario.bossName)
        Target Language: \(targetLang)
        User Objective: \(scenario.objective)
        
        TRANSCRIPT:
        \(transcript)
        
        Evaluate whether the User successfully completed their objective while speaking in \(targetLang).
        IMPORTANT: The transcript is generated by Speech-to-Text software. Ignore any obvious hallucinations, background noise transcriptions, or sudden unexplained shifts in language (e.g., random words in Welsh, Hindi, etc.) that do not make sense in context. Evaluate based on the user's clear intents. If the user spoke in a language other than \(targetLang) instead of practicing \(targetLang), they did not complete the objective.
        
        You must output ONLY a valid JSON object matching the following schema exactly, with no markdown formatting or backticks:
        {
            "task_completed": boolean,
            "fluency_score": integer between 0 and 100,
            "feedback_message": "string providing short, constructive feedback on their performance in \(feedbackLang)"
        }
        
        CRITICAL RULE: The "feedback_message" field MUST be written in \(feedbackLang). Do NOT write the feedback in English if \(feedbackLang) is requested.
        """
    }
}
